version: '3.9'

services:
  build:
    build:
      network: host
      context: .
      args:
        IMAGE_STEAMCMD_NAME: ${IMAGE_STEAMCMD_NAME}
        IMAGE_STEAMCMD_VERSION: ${IMAGE_STEAMCMD_VERSION}
        BUILD_GAME_ID: ${BUILD_GAME_ID}
      cache_from:
      - ${IMAGE_STEAMCMD_NAME}:${IMAGE_STEAMCMD_VERSION}
      - ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_VERSION}
    image: ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_VERSION}
    profiles:
    - build

  server:
    image: ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_VERSION}
    secrets:
    - admin_password
    env_file:
    - .env.server
    ports:
    - "27015:27015/tcp"
    - "27015:27015/udp"
    - "8766-8767:8766-8767/udp"
    - "16261-16262:16261-16262/udp"
    healthcheck:
      test: nc -z localhost 27015
      interval: 10s
      timeout: 2s
      retries: 25
      start_period: 45s
    deploy:
      resources:
        reservations:
          cpus: ${DEPLOY_CPU_RESERVATION}
          memory: ${DEPLOY_MEMORY_RESERVATION}
        limits:
          cpus: ${DEPLOY_CPU_LIMIT}
          memory: ${DEPLOY_MEMORY_LIMIT}
    volumes:
    - ./server/.docker/data/Steam:/home/steam/Steam
    - ./server/.docker/data/server:/home/steam/server
    - ./server/.docker/data/Zomboid:/home/steam/Zomboid

secrets:
  admin_password:
    file: ./server/.docker/secrets/admin_password.txt
    name: admin_password