version: '3.9'

services:
  global:
    build:
      target: install
      network: host
      args:
        IMAGE_ALPINE_NAME: ${IMAGE_ALPINE_NAME}
        IMAGE_ALPINE_VERSION: ${IMAGE_ALPINE_VERSION}
        IMAGE_DEBIAN_NAME: ${IMAGE_DEBIAN_NAME}
        IMAGE_DEBIAN_VERSION: ${IMAGE_DEBIAN_VERSION}
      cache_from:
      - ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_VERSION}
    image: ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_VERSION}
