version: '3.9'

services:
  steamcmd:
    build:
      target: build
      args:
        IMAGE_ALPINE_NAME: ${IMAGE_ALPINE_NAME}
        IMAGE_ALPINE_VERSION: ${IMAGE_ALPINE_VERSION}
        IMAGE_DEBIAN_NAME: ${IMAGE_DEBIAN_NAME}
        IMAGE_DEBIAN_VERSION: ${IMAGE_DEBIAN_VERSION}
        GAME_ID: ${GAME_ID}
    image: testowo-steam
  server:
    build:
      target: install
      args:
        IMAGE_ALPINE_NAME: ${IMAGE_ALPINE_NAME}
        IMAGE_ALPINE_VERSION: ${IMAGE_ALPINE_VERSION}
        IMAGE_DEBIAN_NAME: ${IMAGE_DEBIAN_NAME}
        IMAGE_DEBIAN_VERSION: ${IMAGE_DEBIAN_VERSION}
        GAME_ID: ${GAME_ID}
    image: testowo-server
